# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            cite
tagline:          'The CITE ibrary'
description:      'cite is a JVM library for working with CTS URNs, TextInventories, and CITE URNs'
baseurl: '/cite'


author:
  name:           'Neel Smith'
 

paginate:         5

github:
  repo:           https://github.com/neelsmith/cite

version:          0.12.0

links:
  - title: Live specification
    url: /specs/cite/Cite.html
  - title: API docs
    url: /api
  - title: Github project
    url: https://github.com/cite-architecture/cite
    external: true
  - title: CITE architecture home page
    url: http://cite-architecture.github.io/
    external: true
   